server {
    listen       80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        # This line tells Nginx to look for login.html when someone visits '/'
        index  login.html; 
    }
}
